#!/bin/bash
cd "/Users/judyhuynh/Downloads/Numerology Tidbyt"
/opt/homebrew/bin/pixlet render numerology.star
/opt/homebrew/bin/pixlet push --installation-id "numerology" --api-token "eyJhbGciOiJFUzI1NiIsImtpZCI6IjY1YzFhMmUzNzJjZjljMTQ1MTQyNzk5ODZhMzYyNmQ1Y2QzNTI0N2IiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJodHRwczovL2FwaS50aWRieXQuY29tIiwiZXhwIjozMzUxMzgzODEyLCJpYXQiOjE3NzQ1ODM4MTIsImlzcyI6Imh0dHBzOi8vYXBpLnRpZGJ5dC5jb20iLCJzdWIiOiJVQnVxZklNSTBIWVFHZXFVRFB4U1lXQmU0SjEzIiwic2NvcGUiOiJkZXZpY2UiLCJkZXZpY2UiOiJqZXJraWx5LWNvc21pYy1saXZpbmctbWFybW90LWRhZSJ9.tafBceveax2pkphq7LpRtySucUzIdtjbiY6BQ888Q3WqlCvgHAyJfHUTuYr_PW9993CkHHJpxuAeGJ8fMHhZnw" "jerkily-cosmic-living-marmot-dae" numerology.webp
